language: r
warnings_are_errors: true
sudo: required

env:
  global:
    - PKG=DEV
    - PKG=STD
    - CRAN: http://cran.rstudio.com
    - RGL_USE_NULL: true

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - freeglut3-dev
  - xvfb
  - xserver-xorg-core
  - xserver-xorg
  - xorg
  - openbox
  - xauth
  - libcurl4-openssl-dev
  - curl

r_github_packages:
  - hadley/devtools
  - jimhester/covr
  - terrytangyuan/lfda

before_install:
  - if [[ "$PKG" == "DEV" ]]; then
    - echo "Building development branch..."
    fi
  - if [[ "$PKG" == "STD" ]]; then
    - echo "Building standard branch..."
    fi
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - Rscript -e 'devtools::load_all(); devtools::test()'
